site_name: Canvas Collections
site_url: https://djplaner.github.io/canvas-collections/
repo_url: https://github.com/djplaner/canvas-collections
edit_uri: edit/main/docs/
site_author: David Jones
site_description: >-
  Improve the visual identity and information architecture of the Canvas LMS Modules page

theme:
  name: material
  logo: assets/collections-logo.png
  palette:
    - scheme: collections
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: .overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - header.autohide
    - search.suggest

plugins:
  - search

extra_css: 
  - stylesheets/extra.css 
  - https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0/dist/themes/light.css
extra_javascript: 
  - https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0/dist/shoelace.js


markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/djplaner

nav:
  - Home: index.md
  - Getting Started: #getting-started.md
    - Overview: getting-started/overview.md
    - 1. Install: 
      - Types and Pre-requisites: getting-started/install/types-pre-requisites.md
      - Individual: getting-started/install/individual.md
      - Institutional: getting-started/install/institutional.md
      - Is it working?: getting-started/install/is-it-working.md
    - 2. ğŸš§ Collections 101: getting-started/play/collections-101.md
    - 3. Design for Collections:
      - ğŸš§ Configuration: getting-started/configure/configuration.md
      - ğŸš§ Collections: getting-started/configure/collections.md
      - ğŸš§ Modules: getting-started/configure/modules.md
    - 4. ğŸš§ Use Collections: getting-started/use/types.md
#    - 5. ğŸš§ Configure Claytons Collections:
  - 'ğŸš§ How-tos': 
    - Available walk throughs: walk-throughs/available.md
#    - New course:
#      - Before & after: walk-throughs/new/before-and-after.md
#      - Design: walk-throughs/new/design.md
#      - Configure Collections: walk-throughs/new/configure-collections.md
#      - Configure Modules: walk-throughs/new/configure-modules.md
#      - Set up "Claytons": walk-throughs/new/set-up-claytons.md
#    - Making changes:
#      - Add a collection: walk-throughs/changes/add-a-collection.md
#      - Delete a collection: walk-throughs/changes/delete-a-collection.md
#      - Add a module: walk-throughs/changes/add-a-module.md
#    - Course copy:
#      - Course copy process: walk-throughs/course-copy/process.md
#    - âš—ï¸ Advanced:
#      - Multi-collection, one page Claytons: walk-throughs/advanced/multi-collection-one-page.md
#      - Fix Claytons Card CSS: walk-throughs/advanced/fix-claytons-card-css.md
#    - Navigating the site: 
#      - Student - live: walk-throughs/navigating/student-live.md
#      - Student - Claytons: walk-throughs/navigating/student-claytons.md
#  - ğŸš§ Reference: 
#      - Overview: reference/overview.md
#      - Visibility: reference/visibility.md
#      - Collections:
#        - Collections: reference/collections/overview.md
#      - Representations:
#        - Representations: reference/representations/overview.md
#        - Claytons: reference/representations/claytons/overview.md
#      - Objects (Modules):
#        - Objects: reference/objects/overview.md
#      - Development:
#        - Component Structure: reference/development/component-structure.md
#  - ğŸš§ Development:
#      - Local development: getting-started/development/local-development.md
  - 'ğŸš§ Related Work': related-work.md
  - 'ğŸš§ Latest Version': latest-version.md
#  - âš°ï¸ Features & Use: 
#    - Overview: features.md
#    - Collections: features/collections.md
#    - Representations: features/representations.md
#    - Objects: features/objects.md